packages:
  - packages/*

catalog:
  tsup: ^8.5.0
  typescript: ^5.8.3
  better-auth: 1.2.9
  vitest: ^3.2.4
  zod: "^3.25.67"
  lodash-es: "^4.17.21"
  "@types/lodash-es": "^4.17.12"
  '@types/node': ^24.0.3
